FROM golang:1.26.4-alpine AS builder
WORKDIR /app
COPY go.mod .
COPY main.go .
RUN go build -o server .

FROM alpine:3
RUN apk add --no-cache wget
COPY --from=builder /app/server /server
EXPOSE 8080
CMD ["/server"]